//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4927
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CslaEx.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CslaEx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal must be of type BusinessPrincipal, not.
        /// </summary>
        internal static string BusinessPrincipalException {
            get {
                return ResourceManager.GetString("BusinessPrincipalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changing an element is an invalid operation.
        /// </summary>
        internal static string ChangeInvalidException {
            get {
                return ResourceManager.GetString("ChangeInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can not directly mark a child object for deletion - use its parent collection.
        /// </summary>
        internal static string ChildDeleteException {
            get {
                return ResourceManager.GetString("ChildDeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear is an invalid operation.
        /// </summary>
        internal static string ClearInvalidException {
            get {
                return ResourceManager.GetString("ClearInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid operation - create not allowed.
        /// </summary>
        internal static string CreateNotSupportedException {
            get {
                return ResourceManager.GetString("CreateNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid operation - delete not allowed.
        /// </summary>
        internal static string DeleteNotSupportedException {
            get {
                return ResourceManager.GetString("DeleteNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error reading value:.
        /// </summary>
        internal static string ErrorReadingValueException {
            get {
                return ResourceManager.GetString("ErrorReadingValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid operation - execute not allowed.
        /// </summary>
        internal static string ExecuteNotSupportedException {
            get {
                return ResourceManager.GetString("ExecuteNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a failed on the server.
        /// </summary>
        internal static string FailedOnServer {
            get {
                return ResourceManager.GetString("FailedOnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid operation - fetch not allowed.
        /// </summary>
        internal static string FetchNotSupportedException {
            get {
                return ResourceManager.GetString("FetchNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Business object must supply a non-null ID value in GetIdValue.
        /// </summary>
        internal static string GetIdValueCantBeNull {
            get {
                return ResourceManager.GetString("GetIdValueCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert is an invalid operation.
        /// </summary>
        internal static string InsertInvalidException {
            get {
                return ResourceManager.GetString("InsertInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid operation - insert not allowed.
        /// </summary>
        internal static string InsertNotSupportedException {
            get {
                return ResourceManager.GetString("InsertNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} lower case required.
        /// </summary>
        internal static string LCaseStringRequiredRule {
            get {
                return ResourceManager.GetString("LCaseStringRequiredRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} can not exceed {1}.
        /// </summary>
        internal static string MaxValueRule {
            get {
                return ResourceManager.GetString("MaxValueRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a method call failed.
        /// </summary>
        internal static string MethodCallFailed {
            get {
                return ResourceManager.GetString("MethodCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a not implemented.
        /// </summary>
        internal static string MethodNotImplemented {
            get {
                return ResourceManager.GetString("MethodNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} can not be less than {1}.
        /// </summary>
        internal static string MinValueRule {
            get {
                return ResourceManager.GetString("MinValueRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ApplyEdit is not valid on a child object.
        /// </summary>
        internal static string NoApplyEditChildException {
            get {
                return ResourceManager.GetString("NoApplyEditChildException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BeginEdit is not valid on a child object.
        /// </summary>
        internal static string NoBeginEditChildException {
            get {
                return ResourceManager.GetString("NoBeginEditChildException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CancelEdit is not valid on a child object.
        /// </summary>
        internal static string NoCancelEditChildException {
            get {
                return ResourceManager.GetString("NoCancelEditChildException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid for root objects - use Delete instead.
        /// </summary>
        internal static string NoDeleteRootException {
            get {
                return ResourceManager.GetString("NoDeleteRootException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No principal object should be passed to DataPortal when using Windows integrated security.
        /// </summary>
        internal static string NoPrincipalAllowedException {
            get {
                return ResourceManager.GetString("NoPrincipalAllowedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can not directly save a child object.
        /// </summary>
        internal static string NoSaveChildException {
            get {
                return ResourceManager.GetString("NoSaveChildException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Object is still being edited and can not be saved.
        /// </summary>
        internal static string NoSaveEditingException {
            get {
                return ResourceManager.GetString("NoSaveEditingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Object is not valid and can not be saved.
        /// </summary>
        internal static string NoSaveInvalidException {
            get {
                return ResourceManager.GetString("NoSaveInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No such value exists:.
        /// </summary>
        internal static string NoSuchValueExistsException {
            get {
                return ResourceManager.GetString("NoSuchValueExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argument must not be null.
        /// </summary>
        internal static string NothingNotValid {
            get {
                return ResourceManager.GetString("NothingNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} number required.
        /// </summary>
        internal static string NumberStringRequiredRule {
            get {
                return ResourceManager.GetString("NumberStringRequiredRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parent value can only be set for child objects.
        /// </summary>
        internal static string ParentSetException {
            get {
                return ResourceManager.GetString("ParentSetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type parameter must be a primitive type.
        /// </summary>
        internal static string PrimitiveTypeRequired {
            get {
                return ResourceManager.GetString("PrimitiveTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Property copy failed.
        /// </summary>
        internal static string PropertyCopyFailed {
            get {
                return ResourceManager.GetString("PropertyCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Property get not allowed.
        /// </summary>
        internal static string PropertyGetNotAllowed {
            get {
                return ResourceManager.GetString("PropertyGetNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Property set not allowed.
        /// </summary>
        internal static string PropertySetNotAllowed {
            get {
                return ResourceManager.GetString("PropertySetNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} does not match regular expression.
        /// </summary>
        internal static string RegExMatchRule {
            get {
                return ResourceManager.GetString("RegExMatchRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove is an invalid operation.
        /// </summary>
        internal static string RemoveInvalidException {
            get {
                return ResourceManager.GetString("RemoveInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a t.
        /// </summary>
        internal static string SmartDateT {
            get {
                return ResourceManager.GetString("SmartDateT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a today.
        /// </summary>
        internal static string SmartDateToday {
            get {
                return ResourceManager.GetString("SmartDateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tom.
        /// </summary>
        internal static string SmartDateTom {
            get {
                return ResourceManager.GetString("SmartDateTom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tomorrow.
        /// </summary>
        internal static string SmartDateTomorrow {
            get {
                return ResourceManager.GetString("SmartDateTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a y.
        /// </summary>
        internal static string SmartDateY {
            get {
                return ResourceManager.GetString("SmartDateY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a yesterday.
        /// </summary>
        internal static string SmartDateYesterday {
            get {
                return ResourceManager.GetString("SmartDateYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} can not exceed {1} characters.
        /// </summary>
        internal static string StringMaxLengthRule {
            get {
                return ResourceManager.GetString("StringMaxLengthRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a String value can not be converted to a date.
        /// </summary>
        internal static string StringToDateException {
            get {
                return ResourceManager.GetString("StringToDateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} upper case required.
        /// </summary>
        internal static string UCaseStringRequiredRule {
            get {
                return ResourceManager.GetString("UCaseStringRequiredRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid operation - update not allowed.
        /// </summary>
        internal static string UpdateNotSupportedException {
            get {
                return ResourceManager.GetString("UpdateNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value is not a SmartDate.
        /// </summary>
        internal static string ValueNotSmartDateException {
            get {
                return ResourceManager.GetString("ValueNotSmartDateException", resourceCulture);
            }
        }
    }
}
