//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CslaEx.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CslaEx.Resources.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entre.
        /// </summary>
        internal static string OPERATION_BETWEEN {
            get {
                return ResourceManager.GetString("OPERATION_BETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contiene.
        /// </summary>
        internal static string OPERATION_CONTAINS {
            get {
                return ResourceManager.GetString("OPERATION_CONTAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distinto.
        /// </summary>
        internal static string OPERATION_DISTINCT {
            get {
                return ResourceManager.GetString("OPERATION_DISTINCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string OPERATION_EQUAL {
            get {
                return ResourceManager.GetString("OPERATION_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string OPERATION_GREATER {
            get {
                return ResourceManager.GetString("OPERATION_GREATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        internal static string OPERATION_GREATEROREQUAL {
            get {
                return ResourceManager.GetString("OPERATION_GREATEROREQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string OPERATION_LESS {
            get {
                return ResourceManager.GetString("OPERATION_LESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string OPERATION_LESSOREQUAL {
            get {
                return ResourceManager.GetString("OPERATION_LESSOREQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contiene.
        /// </summary>
        internal static string OPERATION_OP_CONTAINS {
            get {
                return ResourceManager.GetString("OPERATION_OP_CONTAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&gt;.
        /// </summary>
        internal static string OPERATION_OP_DISTINCT {
            get {
                return ResourceManager.GetString("OPERATION_OP_DISTINCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string OPERATION_OP_EQUAL {
            get {
                return ResourceManager.GetString("OPERATION_OP_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string OPERATION_OP_GREATER {
            get {
                return ResourceManager.GetString("OPERATION_OP_GREATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        internal static string OPERATION_OP_GREATEROREQUAL {
            get {
                return ResourceManager.GetString("OPERATION_OP_GREATEROREQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string OPERATION_OP_LESS {
            get {
                return ResourceManager.GetString("OPERATION_OP_LESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string OPERATION_OP_LESSOREQUAL {
            get {
                return ResourceManager.GetString("OPERATION_OP_LESSOREQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empieza por.
        /// </summary>
        internal static string OPERATION_OP_STARTSWITH {
            get {
                return ResourceManager.GetString("OPERATION_OP_STARTSWITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empieza por.
        /// </summary>
        internal static string OPERATION_STARTSWITH {
            get {
                return ResourceManager.GetString("OPERATION_STARTSWITH", resourceCulture);
            }
        }
    }
}
